# docker run --name anime-api -e POSTGRESQL_USERNAME=anime -e POSTGRESQL_PASSWORD=anime -e POSTGRESQL_DATABASE=anime bitnami/postgresql:latest

# VERSAO DO DOCKER-COMPOSE

services:
  postgress: 
    container_name: anime-api-clean
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: anime-api

  # PROD
  # anime-api-clean:
  #   image: bitnami/postgresql
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRESQL_USERNAME=anime-api-api
  #     - POSTGRESQL_PASSWORD=anime-api
  #     - POSTGRESQL_DATABASE=anime-api